spring:
  datasource:
    url: jdbc:h2:mem:.
    driver-class-name: org.h2.Driver
    username: sa
    password: password

server:
  port: 8083
petadoption:
  security:
    client-secret: 16092ceb-a272-4e02-a286-abc28a3b1b97
    client-id: pet-service